-- Create the sales_data table
CREATE TABLE IF NOT EXISTS sales_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  product TEXT NOT NULL,
  channel TEXT NOT NULL,
  orders INTEGER NOT NULL DEFAULT 0,
  revenue DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  visitors INTEGER NOT NULL DEFAULT 0,
  customers INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE sales_data ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access (if needed for the dashboard)
CREATE POLICY "Allow public read access" ON sales_data
  FOR SELECT USING (true);
